#!/usr/bin/env node
// Maintains the generated feature-status index in docs/root.md.
//
//   node scripts/docs-index.mjs          print the index block and validation results
//   node scripts/docs-index.mjs --fix    rewrite the docs-index block in docs/root.md
//   node scripts/docs-index.mjs --check  exit 1 if the block is stale or headers are invalid
//
// New-style docs live in docs/features/<name>/{feature.md,plan.md}. Legacy flat
// docs (docs/features/*.md, docs/ideas/, docs/planning/) are listed as-is and
// not validated; they migrate lazily per AGENTS.md.

import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const docsDir = join(repoRoot, "docs");
const rootMd = join(docsDir, "root.md");
const BEGIN = "<!-- docs-index:begin -->";
const END = "<!-- docs-index:end -->";
const PLAN_STATUSES = new Set(["Draft", "On Hold", "Ready", "In Progress", "Blocked"]);

const mode = process.argv.includes("--fix") ? "fix" : process.argv.includes("--check") ? "check" : "print";
const errors = [];
const rel = (p) => p.slice(repoRoot.length + 1);

function header(file) {
  const head = readFileSync(file, "utf8").split("\n").slice(0, 30).join("\n");
  const get = (name) => head.match(new RegExp(`^${name}:\\s*(.+)$`, "m"))?.[1].trim();
  return { status: get("Status"), created: get("Created"), updated: get("Updated") };
}

function checkDate(file, label, value) {
  if (!value) errors.push(`${rel(file)}: missing ${label}:`);
  else if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) errors.push(`${rel(file)}: ${label}: "${value}" is not YYYY-MM-DD`);
}

const entries = [];
const legacy = [];

const featuresDir = join(docsDir, "features");
if (existsSync(featuresDir)) {
  for (const name of readdirSync(featuresDir).sort()) {
    const dir = join(featuresDir, name);
    if (statSync(dir).isDirectory()) {
      const featureMd = join(dir, "feature.md");
      const planMd = join(dir, "plan.md");
      if (!existsSync(featureMd) && !existsSync(planMd)) {
        errors.push(`${rel(dir)}: contains neither feature.md nor plan.md`);
        continue;
      }
      const parts = [];
      if (existsSync(featureMd)) {
        const h = header(featureMd);
        if (h.status) errors.push(`${rel(featureMd)}: feature.md must not carry Status: (reality has no status)`);
        checkDate(featureMd, "Created", h.created);
        checkDate(featureMd, "Updated", h.updated);
        parts.push(`[feature](features/${name}/feature.md)`);
      }
      if (existsSync(planMd)) {
        const h = header(planMd);
        if (!h.status) errors.push(`${rel(planMd)}: missing Status:`);
        else if (!PLAN_STATUSES.has(h.status))
          errors.push(`${rel(planMd)}: Status "${h.status}" is not one of: ${[...PLAN_STATUSES].join(", ")}`);
        checkDate(planMd, "Created", h.created);
        checkDate(planMd, "Updated", h.updated);
        parts.push(`[plan](features/${name}/plan.md): ${h.status ?? "?"}${h.updated ? `, updated ${h.updated}` : ""}`);
      }
      entries.push(`- **${name}** — ${parts.join(" · ")}`);
    } else if (name.endsWith(".md")) {
      const h = header(dir);
      legacy.push(`- [features/${name.replace(/\.md$/, "")}](features/${name})${h.status ? ` — ${h.status}` : ""}`);
    }
  }
}

for (const sub of ["ideas", "planning"]) {
  const dir = join(docsDir, sub);
  if (!existsSync(dir)) continue;
  for (const name of readdirSync(dir).sort()) {
    if (!name.endsWith(".md")) continue;
    const h = header(join(dir, name));
    legacy.push(`- [${sub}/${name.replace(/\.md$/, "")}](${sub}/${name})${h.status ? ` — ${h.status}` : ""}`);
  }
}

const lines = [
  BEGIN,
  "",
  "_Generated by `scripts/docs-index.mjs --fix` — do not edit this block by hand._",
  "",
  "### Features",
  "",
  ...(entries.length ? entries : ["_None yet._"]),
];
if (legacy.length) lines.push("", "### Legacy documents (pre-migration)", "", ...legacy);
lines.push("", END);
const block = lines.join("\n");

if (mode === "print") {
  console.log(block);
} else {
  const text = existsSync(rootMd) ? readFileSync(rootMd, "utf8") : "";
  const begin = text.indexOf(BEGIN);
  const end = text.indexOf(END);
  const hasBlock = begin !== -1 && end > begin;
  const current = hasBlock ? text.slice(begin, end + END.length) : null;

  if (mode === "fix") {
    const next = hasBlock
      ? text.slice(0, begin) + block + text.slice(end + END.length)
      : `${text.replace(/\n*$/, "\n\n")}${block}\n`;
    if (next !== text) {
      writeFileSync(rootMd, next);
      console.log(`${rel(rootMd)}: index block ${hasBlock ? "updated" : "appended"}`);
    } else {
      console.log(`${rel(rootMd)}: index block already current`);
    }
  } else if (!hasBlock) {
    errors.push(`${rel(rootMd)}: docs-index markers not found — run with --fix to add the block`);
  } else if (current !== block) {
    errors.push(`${rel(rootMd)}: index block is stale — run: node scripts/docs-index.mjs --fix`);
  }
}

if (errors.length) {
  console.error(errors.map((e) => `error: ${e}`).join("\n"));
  process.exit(1);
}
